name: Build and Release

on:
 push:
   branches: [ main, master ]
 pull_request:
   branches: [ main, master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.7.0'

      - name: Install dependencies
        run: npm pkg delete scripts.prepare && rm -rf .husky/.pre-push && yarn

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release@21 --omit=dev --ignore-scripts